apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-mqtt
  namespace: monitoring
  labels:
    app: telegraf-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-mqtt
  template:
    metadata:
      labels:
        app: telegraf-mqtt
    spec:
      containers:
        - name: telegraf
          image: influxdata/telegraf:1.31
          args: ["--config", "/etc/telegraf/telegraf.conf"]
          ports:
            - name: http
              containerPort: 9273
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-mqtt-config
            items:
              - key: telegraf.conf
                path: telegraf.conf
