apiVersion: v1
kind: Service
metadata:
  name: telegraf-mqtt
  namespace: monitoring
  labels:
    app: telegraf-mqtt
spec:
  selector:
    app: telegraf-mqtt
  ports:
    - name: http
      port: 9273
      targetPort: http
